cmake_minimum_required(VERSION 2.8)

PROJECT(dmbacktrace)

PROJECT(dmconfigserver)
INCLUDE(cmake/ModuleImport.cmake)
INCLUDE(cmake/ModuleCompileOptions.cmake)
ModuleSetCompileOptions()

ADD_DEFINITIONS(-DUSE_DMBACKTRACE)

IF (WIN32)
    INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/src/windows)
ENDIF(WIN32)

INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/)
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/include)
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/src)
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/test)

FILE(GLOB_RECURSE DMBACKTRACE_SOURCES
${CMAKE_CURRENT_SOURCE_DIR}/include/*.hpp
${CMAKE_CURRENT_SOURCE_DIR}/include/*.h

${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp
${CMAKE_CURRENT_SOURCE_DIR}/src/*.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/*.c
${CMAKE_CURRENT_SOURCE_DIR}/src/*.hpp
${CMAKE_CURRENT_SOURCE_DIR}/src/*.h
)

IF (WIN32)
    LIST(APPEND DMBACKTRACE_SOURCES)
ENDIF(WIN32)

FILE(GLOB_RECURSE DMBACKTRACETEST_SOURCES
${CMAKE_CURRENT_SOURCE_DIR}/test/*.cpp
${CMAKE_CURRENT_SOURCE_DIR}/test/*.cc
${CMAKE_CURRENT_SOURCE_DIR}/test/*.c
${CMAKE_CURRENT_SOURCE_DIR}/test/*.hpp
${CMAKE_CURRENT_SOURCE_DIR}/test/*.h)

IF (WIN32)
    ADD_LIBRARY(dmbacktrace STATIC ${DMBACKTRACE_SOURCES})
    ADD_EXECUTABLE(dmbacktracetest ${DMBACKTRACETEST_SOURCES})
    TARGET_LINK_LIBRARIES(dmbacktracetest dmbacktrace)
ELSEIF (APPLE)
    ADD_LIBRARY(dmbacktrace ${DMBACKTRACE_SOURCES})
    ADD_EXECUTABLE(dmbacktracetest ${DMBACKTRACETEST_SOURCES})
    TARGET_LINK_LIBRARIES(dmbacktracetest dmbacktrace)
ELSEIF (UNIX)
    ADD_LIBRARY(dmbacktrace ${DMBACKTRACE_SOURCES})
    ADD_EXECUTABLE(dmbacktracetest ${DMBACKTRACETEST_SOURCES})
    TARGET_LINK_LIBRARIES(dmbacktracetest dmbacktrace)
ENDIF ()

#ADD_CUSTOM_COMMAND(
#TARGET dmbacktracetest
#PRE_BUILD
#COMMAND ${CMAKE_COMMAND} -E copy_if_different
#${CMAKE_CURRENT_SOURCE_DIR}/config/test.csv
#$<TARGET_FILE_DIR:dmbacktracetest>
#)

#INSTALL(DIRECTORY include/ DESTINATION include)
#INSTALL(TARGETS dmbacktrace
#        RUNTIME DESTINATION bin
#        LIBRARY DESTINATION lib
#        ARCHIVE DESTINATION lib)

#SET(DMBACKTRACE_LIBS "dmbacktrace")
#MARK_AS_ADVANCED(${DMBACKTRACE_LIBS})